// Associados oficiais da Resorts Brasil (fonte: resortsbrasil.com.br/associados).
// `slug` reservado para as futuras páginas individuais de cada resort.
export interface BrazilResort { slug: string; name: string; uf: string; website: string }

export const BRAZIL_RESORTS: BrazilResort[] = [
  {"slug": "almenat", "name": "Almenat Tapestry Collection by Hilton", "uf": "SP", "website": "https://hotelalmenat.com.br/"},
  {"slug": "blue-tree-thermas-de-lins-resort", "name": "blue tree thermas de lins resort", "uf": "SP", "website": "http://bluetreethermasdelins.com.br/"},
  {"slug": "bourbon-atibaia-resort", "name": "bourbon atibaia", "uf": "SP", "website": "https://www.bourbon.com.br/hotel/bourbon-atibaia"},
  {"slug": "casa-grande-hotel-resort-spa", "name": "casa grande hotel resort", "uf": "SP", "website": "https://www.casagrandehotel.com.br/"},
  {"slug": "clara-resorts", "name": "clara resorts", "uf": "SP", "website": "https://www.clararesorts.com.br/"},
  {"slug": "clubmed", "name": "clubmed", "uf": "SP", "website": "https://www.clubmed.com.br/r/lake-paradise/y"},
  {"slug": "japy-golf-resort-hotel", "name": "japy golf resort hotel", "uf": "SP", "website": "https://www.japygolfresort.com.br/"},
  {"slug": "cyan-resort", "name": "cyan resort", "uf": "SP", "website": "https://www.reserveatlantica.com.br/hotel/cyan-resort"},
  {"slug": "fazenda-dona-carolina", "name": "Hotel Histórico Dona Carolina", "uf": "SP", "website": "https://www.hotelfazendadonacarolina.com.br/"},
  {"slug": "resort-fazenda-sao-joao", "name": "Resort Fazenda São João", "uf": "SP", "website": "https://hotelfazendasaojoao.com.br/"},
  {"slug": "grand-hotel-campos-do-jordao", "name": "Grand Hotel Campos do Jordão", "uf": "SP", "website": "https://grandehotelsenac.com.br/ghj_hotel/grande-hotel-campos-do-jordao/"},
  {"slug": "grand-hotel-sao-pedro", "name": "Grand Hotel São Pedro", "uf": "SP", "website": "https://grandehotelsenac.com.br/ghp_hotel/grande-hotel-sao-pedro/"},
  {"slug": "hot-beach-resort", "name": "Hot Beach Resort", "uf": "SP", "website": "https://hotbeach.com.br/hot-beach-resort/"},
  {"slug": "hot-beach-celebration", "name": "Hot Beach Celebration", "uf": "SP", "website": "https://hotbeach.com.br/celebration/"},
  {"slug": "hot-beach-raizes", "name": "Hot Beach Raízes", "uf": "SP", "website": "https://hotbeach.com.br/raizes/"},
  {"slug": "hot-beach-suites", "name": "Hot Beach Suites Olimpia", "uf": "SP", "website": "https://hotbeach.com.br/hot-beach-suites/"},
  {"slug": "hotel-jp", "name": "Hotel JP Ribeirão Preto", "uf": "SP", "website": "https://www.nacionalinn.com.br/hoteis/hotel-jp-ribeirao-preto"},
  {"slug": "mavsa", "name": "Mavsa Resort", "uf": "SP", "website": "https://mavsaresort.com/"},
  {"slug": "novotel-itu", "name": "Novotel Itu", "uf": "SP", "website": "https://www.novotelitu.com.br/"},
  {"slug": "royal-palm-plaza-resort-campinas", "name": "Royal Palm Plaza Resort Campinas", "uf": "SP", "website": "https://royalpalm.com.br/"},
  {"slug": "sofitel-jequitimar-guaruja", "name": "Sofitel Jequitimar Guarujá", "uf": "SP", "website": "https://all.accor.com/hotel/6383/index.pt-br.shtml"},
  {"slug": "taua-resort-atibaia", "name": "Tauá Resort Atibaia", "uf": "SP", "website": "https://reservas.tauaresorts.com.br/atibaia"},
  {"slug": "villa-rossa", "name": "Villa Rossa Hotel", "uf": "SP", "website": "https://www.villarossa.com.br/"},
  {"slug": "clubmed-rj", "name": "clubmed", "uf": "RJ", "website": "https://www.clubmed.com.br/r/rio-das-pedras/y"},
  {"slug": "le-canton", "name": "le canton", "uf": "RJ", "website": "https://lecanton.com.br/"},
  {"slug": "clara-arte-resort", "name": "Clara Arte Resort", "uf": "MG", "website": "https://clararesorts.com.br/clara-arte"},
  {"slug": "santissimo-resort", "name": "Santíssimo Resort", "uf": "MG", "website": "https://santissimoresort.com.br/"},
  {"slug": "taua-resort-caete", "name": "tauá resort caete", "uf": "MG", "website": "https://reservas.tauaresorts.com.br/caete"},
  {"slug": "thermas-all-inclusive", "name": "thermas all inclusive", "uf": "MG", "website": "https://www.nacionalinn.com.br/hoteis/hotel-thermas-resort-walter-world"},
  {"slug": "vale-suico-resort", "name": "Vale Suíço Resort", "uf": "MG", "website": "https://www.valesuico.com.br/"},
  {"slug": "china-park-eco-resort", "name": "China Park Eco Resort", "uf": "ES", "website": "https://chinapark.com.br/"},
  {"slug": "blue-tree-daj", "name": "Blue Tree Daj", "uf": "PR", "website": "https://www.bluetreedaj.com.br/"},
  {"slug": "bourbon-cataratas-do-iguacu-thermas-eco-resort", "name": "Bourbon Foz do Iguaçu", "uf": "PR", "website": "https://www.bourbon.com.br/hotel/bourbon-cataratas-do-iguacu"},
  {"slug": "jurema-aguas-quentes", "name": "Jurema Águas Quentes", "uf": "PR", "website": "https://juremaaguasquentes.com.br/"},
  {"slug": "mabu-hoteis-resorts", "name": "Mabu Hotel Curitiba", "uf": "PR", "website": "https://www.hoteismabu.com.br/hoteis/mabu-curitiba-business"},
  {"slug": "recanto-cataratas-thermas-resort", "name": "Recanto Cataratas Thermas Resort", "uf": "PR", "website": "https://www.recantocataratasresort.com.br/"},
  {"slug": "wish-foz-do-iguacu", "name": "Wish Foz do Iguaçu", "uf": "PR", "website": "https://www.wishhotels.com.br/wish-foz-do-iguacu"},
  {"slug": "machadinho-thermas-resort-spa", "name": "Machadinho Thermas Resort Spa", "uf": "RS", "website": "https://machadinhothermas.com.br/"},
  {"slug": "wish-serrano", "name": "Wish Serrano", "uf": "RS", "website": "https://www.wishhotels.com.br/wish-serrano"},
  {"slug": "costao-do-santinho", "name": "Costão do Santinho", "uf": "SC", "website": "https://costao.com.br/"},
  {"slug": "fazzenda-park-hotel", "name": "Fazzenda park hotel", "uf": "SC", "website": "https://www.fazzenda.com.br/"},
  {"slug": "monthez", "name": "Monthez", "uf": "SC", "website": "https://monthez.com.br/"},
  {"slug": "iberostar-grand-amazon", "name": "iberostar grand amazon", "uf": "AM", "website": "https://www.iberostar.com/br/hoteis/manaus/iberostar-grand-amazon/"},
  {"slug": "arcobaleno", "name": "Resort Arcobaleno", "uf": "BA", "website": "https://hotelarcobaleno.com.br/"},
  {"slug": "catussaba-resort-hotel", "name": "catussaba resort hotel", "uf": "BA", "website": "http://www.catussaba.com.br/"},
  {"slug": "cana-brava-all-inclusive-resort", "name": "cana brava all inclusive resort", "uf": "BA", "website": "https://canabravaresort.com.br/"},
  {"slug": "clubmed-ba", "name": "clubmed", "uf": "BA", "website": "https://www.clubmed.com.br/r/trancoso/y"},
  {"slug": "costa-do-sauipe-resorts", "name": "costa do sauipe resorts", "uf": "BA", "website": "https://www.costadosauipe.com.br/"},
  {"slug": "jardim-atlantico", "name": "Jardim Atlântico Beach Resort", "uf": "BA", "website": "https://www.resortjardimatlantico.com.br/"},
  {"slug": "grand-palladium-imbassai", "name": "grand palladium imbassai", "uf": "BA", "website": "https://www.palladiumhotelgroup.com/pt/hoteis/brasil/bahia/grand-palladium-imbassai-resort-spa"},
  {"slug": "iberostar-bahia", "name": "iberostar bahia", "uf": "BA", "website": "https://www.iberostar.com/br/hoteis/praia-do-forte/iberostar-bahia/"},
  {"slug": "iberostar-praia-do-forte", "name": "iberostar praia do forte", "uf": "BA", "website": "https://www.iberostar.com/br/hoteis/praia-do-forte/iberostar-praia-do-forte/"},
  {"slug": "la-torre-resort", "name": "La Torre Resort", "uf": "BA", "website": "https://resortlatorre.com.br/"},
  {"slug": "tivoli-bahia-ecoresort", "name": "tivoli bahia ecoresort", "uf": "BA", "website": "https://www.tivolihotels.com/pt/tivoli-ecoresort-praia-do-forte"},
  {"slug": "toromba", "name": "Toromba Resort", "uf": "BA", "website": "https://tororomba.com.br/"},
  {"slug": "transamerica-resort-comandatuba", "name": "transamerica resort comandatuba", "uf": "BA", "website": "https://www.transamericacomandatuba.com.br/"},
  {"slug": "ipioca-beach", "name": "Ipioca Beach Residence & Resort", "uf": "AL", "website": "https://ipiocabeachresidence.com.br/"},
  {"slug": "japaratinga-louge-resort", "name": "japaratinga louge resort", "uf": "AL", "website": "https://www.japaratingaresort.com.br/pt"},
  {"slug": "jatiuca-hotel-resort", "name": "jatiuca hotel resort", "uf": "AL", "website": "https://www.hoteljatiuca.com.br/"},
  {"slug": "maceio-mar", "name": "Maceió Mar All Inclusive Resort", "uf": "AL", "website": "https://mmehoteis.com.br/maceio-mar-resort/"},
  {"slug": "salinas-maceio-resort", "name": "salinas maceio resort", "uf": "AL", "website": "https://www.salinas.com.br/pt/maceio/"},
  {"slug": "salinas-maragogi-resort", "name": "salinas maragogi resort", "uf": "AL", "website": "https://www.salinas.com.br/pt/maragogi/"},
  {"slug": "pratagy-beach-resort", "name": "pratagy beach resort", "uf": "AL", "website": "https://www.pratagy.com.br/"},
  {"slug": "armacao-resort-porto-de-galinhas", "name": "Armação Resort Porto de Galinhas", "uf": "PE", "website": "https://armacaoresort.com/pt/"},
  {"slug": "enotel-porto-de-galinhas", "name": "Enotel Porto de Galinhas", "uf": "PE", "website": "https://enotelresort.com.br/"},
  {"slug": "nannai", "name": "Nannai", "uf": "PE", "website": "https://www.nannai.com.br/muro-alto/"},
  {"slug": "samoa-villa-resort", "name": "Samoa Villa Resort", "uf": "PE", "website": "https://samoavillaresort.com.br/"},
  {"slug": "serrambi-resort", "name": "Serrambi Resort", "uf": "PE", "website": "https://www.serrambiresort.com/"},
  {"slug": "summerville-all-inclusive-resort", "name": "Summerville All Inclusive Resort", "uf": "PE", "website": "https://www.summervilleresort.com.br/"},
  {"slug": "ocean-palace", "name": "Ocean Palace", "uf": "RN", "website": "https://www.oceanpalace.com.br/"},
  {"slug": "wish-natal", "name": "Wish Natal", "uf": "RN", "website": "https://www.wishhotels.com.br/wish-natal"},
  {"slug": "acqua-beach-park-resort", "name": "acqua beach park resort", "uf": "CE", "website": "https://www.beachpark.com.br/resorts/acqua"},
  {"slug": "suites-beach-park-resort", "name": "suites beach park resort", "uf": "CE", "website": "https://www.beachpark.com.br/resorts/suites"},
  {"slug": "wellness-beach-park-resort", "name": "wellness beach park resort", "uf": "CE", "website": "https://www.beachpark.com.br/resorts/wellness"},
  {"slug": "dom-pedro-laguna", "name": "dom pedro laguna", "uf": "CE", "website": "https://laguna.dompedro.com/pt/"},
  {"slug": "rio-quente-resorts", "name": "rio quente resorts", "uf": "GO", "website": "https://www.rioquente.com.br/"},
  {"slug": "taua-resort-alexania", "name": "tauá resort alexania", "uf": "GO", "website": "https://reservas.tauaresorts.com.br/alexania"},
  {"slug": "malai-manso-resort", "name": "malai manso resort", "uf": "MT", "website": "https://www.malaimansoresort.com.br/"},
  {"slug": "zagaia-eco-resort", "name": "Zagaia Eco Resort", "uf": "MS", "website": "https://zagaia.com.br/"},
];
