// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool({
  name: "list_clients",
  title: "List clients",
  description: "List the signed-in user's CRM clients (most recent first).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25)."),
    search: z.string().optional().describe("Optional case-insensitive name/email substring filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("clients").select("id, name, email, phone, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search && search.trim()) {
      const s = search.trim().replace(/[%,]/g, "");
      q = q.or(`name.ilike.%${s}%,email.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_quotes_default = defineTool2({
  name: "list_quotes",
  title: "List quotes",
  description: "List the signed-in user's quotes (or\xE7amentos), most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 25)."),
    status: z2.string().optional().describe("Optional exact status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("quotes").select("id, client_name, destination, start_date, end_date, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-trips.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_trips_default = defineTool3({
  name: "list_trips",
  title: "List trips",
  description: "List the signed-in user's trips / digital wallets, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25)."),
    upcoming_only: z3.boolean().optional().describe("If true, only trips with end_date >= today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, upcoming_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("trips").select("id, client_name, destination, start_date, end_date, status, created_at").eq("user_id", ctx.getUserId()).order("start_date", { ascending: false }).limit(limit ?? 25);
    if (upcoming_only) {
      const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      q = q.gte("end_date", today);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-itineraries.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_itineraries_default = defineTool4({
  name: "list_itineraries",
  title: "List itineraries",
  description: "List the signed-in user's itineraries (roteiros), most recent first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("itineraries").select("id, destination, start_date, end_date, status, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { itineraries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mlwwpckahhfsixplxwif";
var mcp_default = defineMcp({
  name: "agentes-de-sonhos-mcp",
  title: "Agentes de Sonhos",
  version: "0.1.0",
  instructions: "Ferramentas do agente de viagens Agentes de Sonhos. Use list_clients para consultar clientes do CRM, list_quotes para or\xE7amentos, list_trips para viagens/carteiras digitais e list_itineraries para roteiros. Todas as ferramentas retornam apenas dados do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_clients_default, list_quotes_default, list_trips_default, list_itineraries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
